import {
    cacheCrudService,
    cacheSearchService,
    deviceService,
    dynamicAppIconService,
    firebaseCrashlyticsService,
    firebaseInstallationService,
    keyValueStorage,
    logBufferService,
    logger,
    notificationService,
    oAuthService,
    permissionService,
    preferenceService,
    sqliteDatabase,
    subscriptionIapService,
} from '../services';

export const useServices = () => ({
    logService: logger,
    logBufferService: logBufferService,
    deviceService: deviceService,
    permissionService: permissionService,
    notificationService: notificationService,
    oauthService: oAuthService,
    dynamicAppIconService: dynamicAppIconService,
    crashlyticsService: firebaseCrashlyticsService,
    firebaseInstallationService: firebaseInstallationService,
    subscriptionIapService: subscriptionIapService,
    preferenceService: preferenceService,
    cacheCrudService: cacheCrudService,
    cacheSearchService: cacheSearchService,
    keyValueStorage: keyValueStorage,
    sqliteDatabase: sqliteDatabase,
});
