export interface SignaturePayload {
    /** First HMAC key. Which key this is — a relay socket's `$auth.id` or a cloud socket's
     * `Token.authId` — is the caller's choice; this lib only computes with what it is given. */
    authId: string;
    accountId: string;
    identityId: string;
    /** Never read. The formula's 4th `data` slot is the empty string, so any value here produces
     * the same signature. The field exists so call sites can pass their token object unchanged. */
    identityToken: string;
}

export interface SignatureContext {
    /** ISO 8601, generated by the caller. The server recomputes the HMAC with the `current` it
     * received, so this value and the one on the packet must be the same instant. */
    current: string;
    /** The User-Agent the transport actually sends. The server verifies against the UA it
     * received, so an arbitrary constant fails. Always injected; never read from a global. */
    userAgent: string;
}

export interface AuthSignResult {
    signature: string;
    /** Echo of the `current` that went into the signature, so the caller puts the same instant on
     * the packet instead of generating a second one. */
    current: string;
}

export interface IAuthSigner {
    sign(payload: SignaturePayload, context: SignatureContext): AuthSignResult;
}
