use_frameworks! :linkage => :static
use_modular_headers!

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

require_relative '../../../node_modules/react-native-permissions/scripts/setup'
setup_permissions([
  'Camera',
  'PhotoLibrary',
  'Contacts',
  'Notifications',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

project 'Chatic',
  'Debug' => :debug,
  'Release' => :release,
  'Debug Dev' => :debug,
  'Release Dev' => :release

target 'Chatic' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # op-sqlite의 헤더 중복 복사 명령만 깔끔하게 찾아내서 하나를 지우는 스크립트
    installer.pods_project.targets.each do |target|
      if target.name.include?('op-sqlite')
        seen_headers = []
        target.headers_build_phase.files.to_a.each do |file|
          if file.file_ref
            # 파일 이름을 안전하게 가져옵니다
            header_name = file.file_ref.name || file.file_ref.path.split('/').last

            # 이미 목록에 있는 헤더(예: libsql.h)라면 중복이므로 제거합니다
            if seen_headers.include?(header_name)
              target.headers_build_phase.remove_build_file(file)
            else
              seen_headers << header_name
            end
          end
        end
      end
    end
  end
end
