import type { ConfigRegistryModule } from '../types';

/**
 * Endpoints and HTTP retry. No endpoint key includes `'server'` in `writableBy`
 * (ADR-0079 decision 10) — a remote config must not be able to move where the app talks to.
 *
 * `relay.backend`/`relay.wss` are session-scoped QA overrides, matching what `env.ts`
 * already did: an override is a convenience, not something a stray link should pin forever.
 */
export const netModule: ConfigRegistryModule = {
    'net.relay.backend': {
        title: 'Relay backend override',
        description: 'Lets QA point at a different backend via deep link. Cleared when the tab closes.',
        type: 'string',
        defaultValue: '',
        envDefaultKey: 'VITE_DOU_ENDPOINT',
        surface: 'dev',
        writableBy: ['local'],
        persist: 'session',
    },
    'net.relay.wss': {
        title: 'Relay socket override',
        description: 'Lets QA point at a different WebSocket address via deep link. Cleared when the tab closes.',
        type: 'string',
        defaultValue: '',
        envDefaultKey: 'VITE_WS_ENDPOINT',
        surface: 'dev',
        writableBy: ['local'],
        persist: 'session',
    },
    'net.oauth.endpoint': {
        title: 'OAuth endpoint',
        description: 'The address social login exchange requests are sent to.',
        type: 'string',
        defaultValue: '',
        envDefaultKey: 'VITE_OAUTH_ENDPOINT',
        surface: 'internal',
        writableBy: [],
        persist: 'none',
    },
    'net.socialOauth.endpoint': {
        title: 'Social OAuth relay address',
        description: 'The relay address social login authorization requests are sent to.',
        type: 'string',
        defaultValue: '',
        envDefaultKey: 'VITE_SOCIAL_OAUTH_ENDPOINT',
        surface: 'internal',
        writableBy: [],
        persist: 'none',
    },
    'net.iap.endpoint': {
        title: 'In-app purchase endpoint',
        description: 'The address in-app purchase receipt verification requests are sent to.',
        type: 'string',
        defaultValue: '',
        envDefaultKey: 'VITE_IAP_ENDPOINT',
        surface: 'internal',
        writableBy: [],
        persist: 'none',
    },
    'net.admin.backend': {
        title: 'Admin backend address',
        description: 'The backend address admin-v2 calls.',
        type: 'string',
        defaultValue: '',
        envDefaultKey: 'VITE_BACKEND_ENDPOINT',
        surface: 'internal',
        writableBy: [],
        persist: 'none',
    },
    'net.policy.baseUrl': {
        title: 'Policy page base address',
        description: 'The base domain the terms of service and privacy policy links point to.',
        type: 'string',
        defaultValue: 'https://app.chatic.io',
        byStage: { LOCAL: 'https://app-dev.chatic.io', DEV: 'https://app-dev.chatic.io' },
        surface: 'internal',
        writableBy: [],
        persist: 'none',
    },
    'net.deeplink.scheme': {
        title: 'Deep link scheme',
        description: 'The custom URL scheme that opens the app.',
        type: 'string',
        defaultValue: 'chatic',
        byStage: { DEV: 'chatic-dev' },
        surface: 'internal',
        writableBy: [],
        persist: 'none',
    },
    'net.deeplink.desktopProtocol': {
        title: 'Desktop protocol scheme',
        description: 'The custom protocol that opens the desktop app.',
        type: 'string',
        defaultValue: 'chatic',
        envDefaultKey: 'VITE_DESKTOP_PROTOCOL',
        surface: 'internal',
        writableBy: [],
        persist: 'none',
    },
    'net.retry.maxRetries': {
        title: 'HTTP retry count',
        description: 'The maximum number of times a failed request is retried.',
        type: 'number',
        defaultValue: 4,
        surface: 'dev',
        writableBy: ['local', 'server'],
        persist: 'session',
        appliesAt: 'live',
    },
    'net.retry.baseDelayMs': {
        title: 'HTTP retry base delay',
        description: 'The base wait time between retries. Doubles with each attempt.',
        type: 'number',
        defaultValue: 1000,
        surface: 'dev',
        writableBy: ['local', 'server'],
        persist: 'session',
        appliesAt: 'live',
    },
};
